name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "LIBCLANG_PATH=$((gcm clang).source -replace 'clang.exe')" >> $env:GITHUB_ENV
      - uses: dtolnay/rust-toolchain@stable
      - name: Patch red4ext-sys
        run: |
          cargo fetch
          $glue = Get-ChildItem -Recurse -Filter "glue.hpp" $env:USERPROFILE\.cargo | Where-Object { $_.FullName -like "*red4ext-sys*" }
          (Get-Content $glue.FullName) -replace 'RED4EXT_RUNTIME_LATEST', 'RED4EXT_RUNTIME_INDEPENDENT' -replace 'RED4EXT_SDK_LATEST', 'RED4EXT_V0_SEMVER(0, 5, 0)' | Set-Content $glue.FullName
      - run: cargo build --release
      - run: mkdir staging
      - name: Create a mod archive
        working-directory: staging
        run: |
          mkdir -p ./red4ext/plugins
          mkdir -p ./r6/scripts
          cp -R ../reds/* ./r6/scripts
          cp ../target/release/*.dll ./red4ext/plugins/
      - uses: actions/upload-artifact@v4
        with:
          path: staging/**/*
